/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health check
         * @description Returns a simple status object confirming the API is reachable.
         */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/articles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List recent articles
         * @description Returns security news articles crawled within the last N days. Defaults to 7 days when the `days` parameter is omitted.
         */
        get: operations["getArticles"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/articles/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get article by ID
         * @description Returns a single security article including its raw HTML content and the cleaned plain-text version used for CVE extraction.
         */
        get: operations["getArticleByID"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/repositories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List watched repositories
         * @description Returns a summary list of all repositories being monitored by Parapet. Each item contains only the identifying fields; use GET /repositories/{id} for dependency and match details.
         */
        get: operations["getRepositories"];
        put?: never;
        /**
         * Add a repository to watch
         * @description Registers a new GitHub (or Bitbucket) repository for dependency and vulnerability monitoring. Once added, the repository's dependency manifest will be fetched during the next pipeline run.
         */
        post: operations["createRepository"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/repositories/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get repository details
         * @description Returns full details for a watched repository including its resolved dependency list and any CVE matches found against those dependencies.
         */
        get: operations["getRepositoryByID"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/vulnerabilities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List all vulnerabilities
         * @description Returns all CVEs extracted from crawled security articles. Each vulnerability includes the affected technologies (with PURL and version range) and the source article IDs it was extracted from.
         */
        get: operations["getVulnerabilities"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pipeline/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Trigger a pipeline run
         * @description Starts the full Parapet pipeline asynchronously. The pipeline runs four sequential stages: (1) harvest new articles, (2) extract CVEs using an LLM, (3) update repository dependencies from source control, (4) match CVEs against dependencies. Returns immediately with 202; poll GET /pipeline/status for results.
         */
        post: operations["runPipeline"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pipeline/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get last pipeline result
         * @description Returns the result of the most recent pipeline run, including counts of articles harvested, vulnerabilities extracted, dependency changes, and matches found. If no run has occurred yet, all counts are zero and RanAt is the zero time ("0001-01-01T00:00:00Z").
         */
        get: operations["getPipelineStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Liveness indicator returned by GET /health */
        HealthResponse: {
            /** @example ok */
            status: string;
        };
        /** @description Standard error envelope returned on 4xx and 5xx responses */
        ErrorResponse: {
            /**
             * @description Human-readable error message
             * @example article not found
             */
            error: string;
        };
        /** @description A security news article crawled from an external source. */
        Article: {
            /**
             * @description Unique article identifier (ULID)
             * @example 01HXYZ1234ABCDEF
             */
            id: string;
            /**
             * Format: uri
             * @description Original URL of the article
             * @example https://www.bleepingcomputer.com/news/security/critical-cve-in-openssl
             */
            source_url: string;
            /**
             * @description Domain of the source that published the article
             * @example bleepingcomputer.com
             * @enum {string}
             */
            host_domain: "hackernews.com" | "bleepingcomputer.com";
            /**
             * Format: date-time
             * @description When the article was published by the source
             */
            published_at: string;
            /**
             * @description Article headline / title
             * @example Critical CVE-2024-1234 Found in OpenSSL
             */
            headline: string;
            /**
             * @description Author of the article as listed by the source
             * @example Lawrence Abrams
             */
            author: string;
            /** @description Raw HTML body of the article as crawled */
            content_html: string;
            /** @description Plain-text version of the article body, stripped of HTML and used as input for CVE extraction by the LLM */
            content_cleaned: string;
            /**
             * Format: date-time
             * @description Timestamp when Parapet crawled the article
             */
            crawled_at: string;
            /**
             * Format: date-time
             * @description Timestamp when the article was processed for CVE extraction. Null if not yet processed.
             */
            processed_at?: string | null;
            /**
             * Format: date-time
             * @description Timestamp of the last update to this record, if any
             */
            updated_at?: string | null;
        };
        /** @description A specific software component affected by a vulnerability */
        AffectedTechnology: {
            /**
             * @description Human-readable package or library name
             * @example openssl
             */
            name: string;
            /**
             * @description Package URL (PURL) uniquely identifying the component, e.g. pkg:golang/github.com/openssl/openssl
             * @example pkg:golang/github.com/openssl/openssl
             */
            purl: string;
            /**
             * @description Version range of the affected component, e.g. "<3.2.1" or ">=1.0.0,<1.1.2"
             * @example <3.2.1
             */
            version_range: string;
        };
        /** @description A CVE extracted from one or more security articles. */
        Vulnerability: {
            /**
             * @description Unique vulnerability identifier (ULID)
             * @example 01HXYZ9999VULNID
             */
            id: string;
            /**
             * @description CVE identifier as published by MITRE/NVD
             * @example CVE-2024-1234
             */
            cve: string;
            /** @description Software components known to be affected by this CVE */
            affected_technologies: components["schemas"]["AffectedTechnology"][];
            /**
             * @description CVSS severity rating
             * @example CRITICAL
             * @enum {string}
             */
            severity: "CRITICAL" | "HIGH" | "MEDIUM" | "LOW";
            /**
             * @description Summary of the vulnerability as extracted from the source article
             * @example A buffer overflow in OpenSSL allows remote code execution.
             */
            description: string;
            /**
             * @description IDs of the articles from which this CVE was extracted
             * @example [
             *       "01HXYZ1234ABCDEF"
             *     ]
             */
            source_article_ids: string[];
            /**
             * Format: date-time
             * @description Date the CVE was publicly disclosed
             */
            published_at: string;
            /**
             * Format: date-time
             * @description Timestamp when this record was created in Parapet
             */
            created_at: string;
        };
        /** @description Summary view of a watched repository returned by GET /repositories */
        RepositoryListItem: {
            /**
             * @description Unique repository identifier (ULID)
             * @example 01HXYZ5678GHIJKL
             */
            id: string;
            /**
             * @description Repository owner / organisation name
             * @example openssl
             */
            owner_name: string;
            /**
             * @description Repository name
             * @example openssl
             */
            repository_name: string;
            /**
             * @description Git hosting provider
             * @example Github.com
             * @enum {string}
             */
            git_provider: "Github.com" | "Bitbucket.com";
        };
        /** @description A dependency detected in a watched repository's manifest. */
        RepositoryDependency: {
            /**
             * @description Unique dependency record identifier (ULID)
             * @example 01HXYZDDDDEPENDE
             */
            id: string;
            /**
             * @description ID of the repository this dependency belongs to
             * @example 01HXYZ5678GHIJKL
             */
            repository_id: string;
            /**
             * @description Package name
             * @example github.com/gorilla/mux
             */
            name: string;
            /**
             * @description Pinned or resolved version
             * @example v1.8.0
             */
            version: string;
            /**
             * @description Package URL (PURL) used to cross-reference against vulnerability affected technologies
             * @example pkg:golang/github.com/gorilla/mux@v1.8.0
             */
            purl: string;
            /**
             * Format: date-time
             * @description Timestamp when this dependency record was first created
             */
            created_at: string;
            /**
             * Format: date-time
             * @description Timestamp of the last time this dependency was matched against a CVE. Null if never matched.
             */
            last_matched_at?: string | null;
        };
        /** @description A confirmed or potential match between a repository dependency and a CVE. */
        Match: {
            /**
             * @description Unique match identifier (ULID)
             * @example 01HXYZMATCHMATCH
             */
            id: string;
            /**
             * @description ID of the matched vulnerability
             * @example 01HXYZ9999VULNID
             */
            vulnerability_id: string;
            /**
             * @description ID of the affected repository
             * @example 01HXYZ5678GHIJKL
             */
            repository_id: string;
            /**
             * @description PURL of the vulnerable component as declared in the CVE
             * @example pkg:golang/github.com/gorilla/mux
             */
            component_purl: string;
            /**
             * @description Name of the dependency in the repository that matched
             * @example github.com/gorilla/mux
             */
            matched_component: string;
            /**
             * @description Version of the dependency that matched the vulnerable range
             * @example v1.8.0
             */
            matched_version: string;
            /**
             * @description Current status of the match
             * @example CONFIRMED
             * @enum {string}
             */
            status: "CONFIRMED" | "WARNING" | "RESOLVED";
            /**
             * Format: date-time
             * @description Timestamp when the match was resolved (e.g. dependency was updated). Null if still active.
             */
            resolved_at?: string | null;
            /**
             * Format: date-time
             * @description Timestamp when this match was first detected
             */
            created_at: string;
        };
        /** @description Full detail view of a watched repository, including its resolved dependencies and any CVE matches found against them. */
        RepositoryDetail: {
            /** @example 01HXYZ5678GHIJKL */
            id: string;
            /** @example openssl */
            owner_name: string;
            /** @example openssl */
            repository_name: string;
            /**
             * @example Github.com
             * @enum {string}
             */
            git_provider: "Github.com" | "Bitbucket.com";
            /**
             * Format: date-time
             * @description When the repository's dependency manifest was last fetched. Null if never fetched.
             */
            last_fetched_at?: string | null;
            /** @description Dependencies detected in the repository's manifest */
            dependencies: components["schemas"]["RepositoryDependency"][];
            /** @description CVE matches found against this repository's dependencies */
            matches: components["schemas"]["Match"][];
        };
        /** @description Request body for registering a new repository to watch */
        CreateRepositoryRequest: {
            /**
             * @description Repository owner or organisation name on the git provider
             * @example openssl
             */
            owner_name: string;
            /**
             * @description Repository name on the git provider
             * @example openssl
             */
            repository_name: string;
            /**
             * @description Git hosting provider
             * @example Github.com
             * @enum {string}
             */
            git_provider: "Github.com" | "Bitbucket.com";
        };
        /** @description Acknowledgement returned immediately when a pipeline run is triggered */
        PipelineStartedResponse: {
            /** @example pipeline started */
            status: string;
        };
        /** @description An error that occurred during a specific pipeline stage */
        PipelineError: {
            /**
             * @description The pipeline stage in which the error occurred
             * @example extract
             * @enum {string}
             */
            stage: "harvest" | "extract" | "update_deps" | "match";
            /**
             * @description Human-readable error message
             * @example failed to fetch articles from bleepingcomputer.com
             */
            error: string;
        };
        /** @description Summary of a completed pipeline run. All counts reflect work done in that single execution. */
        PipelineResult: {
            /**
             * Format: date-time
             * @description Timestamp when this pipeline run started
             */
            ran_at: string;
            /** @description true if the pipeline is currently running */
            run_in_progress?: boolean;
            /**
             * @description Number of new articles crawled and stored during the harvest stage
             * @example 12
             */
            articles_harvested: number;
            /**
             * @description Number of CVEs extracted from articles during the extract stage
             * @example 3
             */
            vulnerabilities_extracted: number;
            /**
             * @description Number of dependency records added during the update-deps stage
             * @example 5
             */
            deps_added: number;
            /**
             * @description Number of dependency records removed during the update-deps stage
             * @example 1
             */
            deps_removed: number;
            /**
             * @description Number of new CVE-to-dependency matches detected during the match stage
             * @example 2
             */
            matches_found: number;
            /** @description Errors encountered across all pipeline stages. An empty array indicates a clean run. */
            errors: components["schemas"]["PipelineError"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Server is healthy */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    getArticles: {
        parameters: {
            query?: {
                /** @description Number of days to look back when filtering articles. Must be a positive integer. Defaults to 7. */
                days?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of articles published within the requested window */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Article"][];
                };
            };
            /** @description The `days` parameter is not a valid positive integer */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": "invalid days parameter"
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Database or internal error while fetching articles */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getArticleByID: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Unique identifier of the article */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The requested article */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Article"];
                };
            };
            /** @description No article found for the given ID */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": "article not found"
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Database or internal error while fetching the article */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getRepositories: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of watched repositories */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RepositoryListItem"][];
                };
            };
            /** @description Database or internal error while fetching repositories */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    createRepository: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateRepositoryRequest"];
            };
        };
        responses: {
            /** @description Repository successfully registered */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RepositoryDetail"];
                };
            };
            /** @description Request body is missing required fields or is malformed */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Database or internal error while saving the repository */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getRepositoryByID: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Unique identifier of the watched repository */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Repository detail with dependencies and vulnerability matches */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RepositoryDetail"];
                };
            };
            /** @description No repository found for the given ID */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": "repository not found"
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Database or internal error while fetching repository data */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getVulnerabilities: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of extracted vulnerabilities */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Vulnerability"][];
                };
            };
            /** @description Database or internal error while fetching vulnerabilities */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    runPipeline: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Pipeline run accepted and started in the background */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PipelineStartedResponse"];
                };
            };
        };
    };
    getPipelineStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Most recent pipeline result (zero values if no run has occurred yet) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PipelineResult"];
                };
            };
        };
    };
}
